### ISSUE TITLE
ERROR: pcap_activate status -1, CAP: generic error code

### ISSUE THREAD

**Issue by Voyotv** [t6x/reaver-wps-fork-t6x#296] opened 2020-01-04 21:10 UTC
Hello

If I try to run the latest in-built version of Wash/Reaver I get this error:

<a href="https://imgur.com/egMnrDl"><img src="https://i.imgur.com/egMnrDl.jpg" title="source: imgur.com" /></a>

So I downgraded to v1.6.1 which runs o.k., but than I get new problems. If I run Reaver on it's own, it just won't associate:

<a href="https://imgur.com/2Xa3CRZ"><img src="https://i.imgur.com/2Xa3CRZ.jpg" title="source: imgur.com" /></a>

If I do the association manually than I get this:

<a href="https://imgur.com/gcP5f7v"><img src="https://i.imgur.com/gcP5f7v.jpg" title="source: imgur.com" /></a>

Wifi chip that I'm using is Realtek RTL8812AU. Injection and everything else seems to work just fine. Anyone knows what could be the problem here?

**Comment by kimocoder** [comment] 2020-01-11 18:56
Download reaver from source, cd "reaver-wps-fork-t6x/src" and "make && make install"

@rofl0r could you tag a new version?

**Comment by Error0x00000001** [comment] 2020-02-06 10:54
kimokoder fork Work! ))

**Comment by kimocoder** [comment] 2020-02-06 10:56
Great

**Comment by jarilaos** [comment] 2020-06-03 23:52
Hi!

Yesterday I updated Reaver from 1.6.5 to 1.6.6 and the issue is fixed. 

I'm using Kali with kernel 5.6 and the latest Realtek RTL8812AU chipset 5.6.4.2~20200529-0kali1.

You could close the issue if you want.

Thanks for all contributions!

**Closed** 2020-06-04 02:12 UTC
