### ISSUE TITLE
Reaver WPS Fork T6X 1.6b - macOS Sierra 10.12.6 compile error

### ISSUE THREAD

**Issue by DJDan** [t6x/reaver-wps-fork-t6x#156] opened 2017-08-09 15:05 UTC
NOTE: Previous version. Approx 1.4 compiled (and worked perfectly with pixiewps).
If someone could please fix the latest build (v1.6b) to both compile/install in macOS Sierra 10.12.6 that would be greatly appreciated.

===

I tried
git clone https://github.com/t6x/reaver-wps-fork-t6x

cd reaver-wps-fork-t6x*/
cd src/
./configure
make

I then get the following error

=======

 make

cp lwe/wireless.21.h lwe/wireless.h

gcc -DCONF_DIR='"/usr/local/var/lib/reaver"' -Wall -g -O2 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-pointer-sign -Ilibwps -I. -Ilwe -DCONFIG_IPV6   -c -o globule.o globule.c

warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'?

      [-Wunknown-warning-option]

In file included from globule.c:34:

In file included from ./globule.h:37:

./defs.h:44:10: fatal error: 'asm/byteorder.h' file not found

#include <asm/byteorder.h>

         ^

1 warning and 1 error generated.

make: *** [globule.o] Error 1

====

I then try the following

gcc -DCONF_DIR='"/usr/local/var/lib/reaver"' -Wall -g -O2 -Wno-unused-variable -Wno-unused-const-variable -Wno-unused-function -Wno-pointer-sign -Ilibwps -I. -Ilwe -DCONFIG_IPV6   -c -o globule.o globule.c

But still get an error like this

===

In file included from globule.c:34:

In file included from ./globule.h:37:

./defs.h:44:10: fatal error: 'asm/byteorder.h' file not found

#include <asm/byteorder.h>

**Comment by rofl0r** [comment] 2017-08-09 15:16
duplicate of https://github.com/t6x/reaver-wps-fork-t6x/issues/145
maybe you can get it to work by reverting the commit mentioned there, but then, what's the point ? afaik there are no compatible drivers in mac os anyway.

**Closed by rofl0r** 2017-08-09 15:16 UTC
